version: "3.9"
services:
  master:
    image: mariadb
    environment:
      - MARIADB_USER=gramja
      - MARIADB_PASSWORD=gramja
      - MARIADB_ROOT_PASSWORD=gramja
      - MARIADB_DATABASE=saas
    volumes:
      - master-data:/var/lib/mysql
    ports:
      - "3306:3306"
  slave:
    image: mariadb
    environment:
      - MARIADB_USER=gramja
      - MARIADB_PASSWORD=gramja
      - MARIADB_ROOT_PASSWORD=gramja
      - MARIADB_DATABASE=saas
    volumes:
      - slave-data:/var/lib/mysql
    ports:
      - "3307:3306"
  app1:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=gramja
    depends_on:
      - "master"
  app2:
    build: .
    ports:
      - "5002:5000"
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=gramja
    depends_on:
      - "master"
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - nginx
volumes:
  master-data:
  slave-data:
