version: "3.9"
services:
  master:
    image: mariadb
    environment:
      - MARIADB_USER=gramja
      - MARIADB_PASSWORD=gramja
      - MARIADB_ROOT_PASSWORD=gramja
      - MARIADB_DATABASE=saas
    networks:
      saasnet: 
        ipv4_address: 172.25.0.13
    volumes:
      - master-data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  slave:
    image: mariadb
    environment:
      - MARIADB_USER=gramja
      - MARIADB_PASSWORD=gramja
      - MARIADB_ROOT_PASSWORD=gramja
      - MARIADB_DATABASE=saas
    networks: 
      saasnet:
        ipv4_address: 172.25.0.15
    volumes:
      - slave-data:/var/lib/mysql/slave

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=gramja
    depends_on:
      - "master"

networks:
  saasnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1

volumes:
  master-data:
  slave-data:
